### ISSUE TITLE
Entity can't be deleted from PluginDbContext

### ISSUE THREAD

**Issue by idchrono** [peterliapin/onlinesales.core#258]
I have created plugin, added required entities, all was good.
After discussion with analitics we decided that one of enitities won't be necessary in the future.
I have deleted it from context and created migration.

When core is started I get next exception "Sequence contains no matching element".
StackTrace:
``` code c#

   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at OnlineSales.Infrastructure.CustomSqlServerMigrationsSqlGenerator.GetIEntityType(IModel model, String tableName) in C:\sources\OnlineSales\onlinesales.core\src\OnlineSales\Infrastructure\CustomSqlServerMigrationsSqlGenerator.cs:line 196
   at OnlineSales.Infrastructure.CustomSqlServerMigrationsSqlGenerator.Generate(DropTableOperation operation, IModel model, MigrationCommandListBuilder builder, Boolean terminate) in C:\sources\OnlineSales\onlinesales.core\src\OnlineSales\Infrastructure\CustomSqlServerMigrationsSqlGenerator.cs:line 71
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.<>c.<.cctor>b__82_18(MigrationsSqlGenerator g, MigrationOperation o, IModel m, MigrationCommandListBuilder b)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(MigrationOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Migrations.NpgsqlMigrationsSqlGenerator.Generate(MigrationOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model, MigrationsSqlGenerationOptions options)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Migrations.NpgsqlMigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model, MigrationsSqlGenerationOptions options)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.GenerateUpSql(Migration migration, MigrationsSqlGenerationOptions options)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.<>c__DisplayClass16_2.<GetMigrationCommandLists>b__2()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
   at OnlineSales.Program.<MigrateOnStartIfRequired>d__9.MoveNext() in C:\sources\OnlineSales\onlinesales.core\src\OnlineSales\Program.cs:line 282
   at OnlineSales.Program.<Main>d__4.MoveNext() in C:\sources\OnlineSales\onlinesales.core\src\OnlineSales\Program.cs:line 142
```

use current develop branch from 2024-04-16

**Comment by idchrono** [comment]
fixed issue with [PR](https://github.com/peterliapin/onlinesales.core/pull/259)

**Comment by idchrono** [comment]
PR merged into develop
